name: iOS Build Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  say-hello-job:
    runs-on: macos-latest  # <--- Change 'IOS' to 'macos-latest'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from macOS runner!"