name: iOS Build Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Install Expo CLI globally
        run: npm install -g expo-cli
      - name: Generate iOS Xcode project
        run: npx --yes expo prebuild --platform ios --no-install
      - name: Install native dependencies
        # Manually run the install with the legacy flag after prebuild
        run: npm install --legacy-peer-deps
      - name: Install iOS Pods (Native Dependencies)
        working-directory: ./ios
        run: pod install
      - name: Build the app
        working-directory: ./ios
        run: |
          xcodebuild build \
            -workspace 'agriFM.xcworkspace' \
            -scheme 'agriFM' \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED='NO'